#!/bin/bash

TMP_DIR=$(mktemp -d)
CWD=$(pwd)

# Always clean up after yourself
cleanup() {
    rm ${TMP_DIR} -rf
    cd "${CWD}"
}

trap cleanup EXIT

SITES_GO="${TMP_DIR}/import.go"

SITES=$(ls sites)

cat <<EOF > "${SITES_GO}"
// Code generated by genimport.sh; DO NOT EDIT
package main

import (
    // Parse command-line args before init()
	_ "server/sites"
    // Call each site's init()
EOF

for SITE in $SITES; do
  if [ ".skeleton" == "${SITE}" ]; then
    continue
  fi

  if [ ! -d "sites/${SITE}" ]; then
    continue
  fi

  echo "	_ \"server/sites/${SITE}\"" >> "${SITES_GO}"
done

echo ")" >> "${SITES_GO}"
cp "${SITES_GO}" .
