// Generated by genstatic.sh
package main

import (
	_ "embed"
)

//go:embed static/img/favicon.ico
var FaviconICO []byte

//go:embed static/css/pico.classless.min.css
var md5e2f05f6ffeed5ed5a4578547268bfea1 []byte

//go:embed static/js/htmx-ws-2.0.3.js
var md5cc1ae11d4f8e72e9be0c15b987fc9696 []byte

//go:embed static/js/htmx-2.0.3.js
var md593063fe04ea37e3b3441590f9abf141a []byte

//go:embed static/js/websocket.js
var md5a420f9a5a16a571083b5e047c7c997d3 []byte

// StaticFiles generated bindings for static files
var StaticFiles = map[string][]byte{
  "/static/img/f114e431508cfafeac5338fe49eeb6bf.ico": FaviconICO, // static/img/favicon.ico
  "/static/css/e2f05f6ffeed5ed5a4578547268bfea1.css": md5e2f05f6ffeed5ed5a4578547268bfea1, // static/css/pico.classless.min.css
  "/static/js/cc1ae11d4f8e72e9be0c15b987fc9696.js": md5cc1ae11d4f8e72e9be0c15b987fc9696, // static/js/htmx-ws-2.0.3.js
  "/static/js/93063fe04ea37e3b3441590f9abf141a.js": md593063fe04ea37e3b3441590f9abf141a, // static/js/htmx-2.0.3.js
  "/static/js/a420f9a5a16a571083b5e047c7c997d3.js": md5a420f9a5a16a571083b5e047c7c997d3, // static/js/websocket.js
}

// StaticFilesContentType mime types for static files
var StaticFilesContentType = map[string]string{
  "/static/img/f114e431508cfafeac5338fe49eeb6bf.ico": "image/vnd.microsoft.icon", // static/img/favicon.ico
  "/static/css/e2f05f6ffeed5ed5a4578547268bfea1.css": "text/css", // static/css/pico.classless.min.css
  "/static/js/cc1ae11d4f8e72e9be0c15b987fc9696.js": "text/javascript", // static/js/htmx-ws-2.0.3.js
  "/static/js/93063fe04ea37e3b3441590f9abf141a.js": "text/javascript", // static/js/htmx-2.0.3.js
  "/static/js/a420f9a5a16a571083b5e047c7c997d3.js": "text/javascript", // static/js/websocket.js
}

// StaticFileNames Resolve actual file names to md5 file names
var StaticFileNames = map[string]string{
  "/static/img/favicon.ico": "/static/img/f114e431508cfafeac5338fe49eeb6bf.ico",
  "/static/css/pico.classless.min.css": "/static/css/e2f05f6ffeed5ed5a4578547268bfea1.css",
  "/static/js/htmx-ws-2.0.3.js": "/static/js/cc1ae11d4f8e72e9be0c15b987fc9696.js",
  "/static/js/htmx-2.0.3.js": "/static/js/93063fe04ea37e3b3441590f9abf141a.js",
  "/static/js/websocket.js": "/static/js/a420f9a5a16a571083b5e047c7c997d3.js",
}
