// Code generated by genstatic.sh; DO NOT EDIT
package _skeleton

import (
	_ "embed"
)

//go:embed static/image/favicon.ico
var FaviconICO []byte

//go:embed static/css/pico.classless.min.css
var md5e2f05f6ffeed5ed5a4578547268bfea1 []byte

//go:embed static/js/htmx-2.0.3.js
var md593063fe04ea37e3b3441590f9abf141a []byte

//go:embed static/js/htmx-ws-2.0.2.js
var md5fa4bdd0019efa4e59fc5d78d7e0a283b []byte

// StaticFiles generated bindings for static files
var StaticFiles = map[string][]byte{
	"/static/image/f114e431508cfafeac5338fe49eeb6bf.ico": FaviconICO,                          // static/image/favicon.ico
	"/static/css/e2f05f6ffeed5ed5a4578547268bfea1.css":   md5e2f05f6ffeed5ed5a4578547268bfea1, // static/css/pico.classless.min.css
	"/static/js/93063fe04ea37e3b3441590f9abf141a.js":     md593063fe04ea37e3b3441590f9abf141a, // static/js/htmx-2.0.3.js
	"/static/js/fa4bdd0019efa4e59fc5d78d7e0a283b.js":     md5fa4bdd0019efa4e59fc5d78d7e0a283b, // static/js/htmx-ws-2.0.2.js
}

// StaticFilesContentType mime types for static files
var StaticFilesContentType = map[string]string{
	"/static/image/f114e431508cfafeac5338fe49eeb6bf.ico": "image/vnd.microsoft.icon", // static/image/favicon.ico
	"/static/css/e2f05f6ffeed5ed5a4578547268bfea1.css":   "text/css",                 // static/css/pico.classless.min.css
	"/static/js/93063fe04ea37e3b3441590f9abf141a.js":     "text/javascript",          // static/js/htmx-2.0.3.js
	"/static/js/fa4bdd0019efa4e59fc5d78d7e0a283b.js":     "text/javascript",          // static/js/htmx-ws-2.0.2.js
}

// StaticFileNames Resolve actual file names to md5 file names
var StaticFileNames = map[string]string{
	"/static/image/favicon.ico":          "/static/image/f114e431508cfafeac5338fe49eeb6bf.ico",
	"/static/css/pico.classless.min.css": "/static/css/e2f05f6ffeed5ed5a4578547268bfea1.css",
	"/static/js/htmx-2.0.3.js":           "/static/js/93063fe04ea37e3b3441590f9abf141a.js",
	"/static/js/htmx-ws-2.0.2.js":        "/static/js/fa4bdd0019efa4e59fc5d78d7e0a283b.js",
}
